api_hash: 071ea901d6271a50e8f86b403b244826
api_id: 29060182
bot_token: 8479394911:AAEXCK8xX0jXYnOF_gcA9wSsu7Z68AjzbR8
chat:
- chat_id: -1002634361114
  last_read_message_id: 489
custom_downloads:
  enable: true
  group_tags:
    '-1002504980730': ç½‘çº¢ä½“è‚²ç”Ÿä¼šå‘˜ç¾¤
    '-1002634361114': Aæˆ˜å£«father2026.08
    '-1001355003597': 03ğŸ”µæ—¥æœ¬ã€JPã€‘new
    '-1002234837448': ğŸ«§æˆ˜å£«father2024.08~2025.08
  target_ids:
    '-1002234837448':
    - 310
    - 311
    - 312
    - 5531
enable_download_txt: true
file_formats:
  audio:
  - all
  document:
  - all
  video:
  - all
file_path_prefix:
- chat_title
language: EN
media_types:
- audio
- video
- video_note
- voice
- animation
- photo
- document
- sticker
save_path: TGDL/unified_downloads
web_port: 5002
bot_save_path: /Users/chriswang/Documents/Py/TGDL/TGDL/unified_downloads
allowed_user_ids:
- 7588743028
